# Generated by Django 4.2.6 on 2023-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloca',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
