# Generated by Django 4.2.6 on 2023-11-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0002_userloca_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloca',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
