# Generated by Django 4.2.7 on 2023-12-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_userloca_address_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloca',
            name='address_mode',
            field=models.IntegerField(default=1),
        ),
    ]
