# Generated by Django 5.0.2 on 2024-04-01 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CartApp', '0003_orders_buyer'),
        ('LandingApp', '0002_userloca_latitude_userloca_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChartLoca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_country', models.CharField(max_length=200, null=True)),
                ('source_state', models.CharField(max_length=200, null=True)),
                ('source_city', models.CharField(max_length=200, null=True)),
                ('sourceLat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('sourceLng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('dest_country', models.CharField(max_length=200, null=True)),
                ('dest_state', models.CharField(max_length=200, null=True)),
                ('dest_city', models.CharField(max_length=200, null=True)),
                ('destLat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('destLng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverUnitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LandingApp.userloca')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentLat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('currentLng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('salary', models.IntegerField(default=0)),
                ('workCount', models.IntegerField(default=0)),
                ('typeOfDelv', models.IntegerField(default=0)),
                ('userauth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_dispatched', models.BooleanField(default=False)),
                ('type_of_dispatch', models.IntegerField(default=0)),
                ('unit_status', models.BooleanField(default=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CartApp.orders')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.deliverunitdata')),
                ('arrival_man', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='DeliveryApp.deliveryman')),
                ('departer_man', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='DeliveryApp.deliveryman')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_man', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.deliveryman')),
                ('destination_delivery_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_shipment_unit', to='DeliveryApp.deliverunit')),
                ('source_delivery_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_shipment_unit', to='DeliveryApp.deliverunit')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CartApp.orders')),
                ('shipment_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.shipmentunit')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverystatus', models.CharField(max_length=200, null=True)),
                ('destinationdeliveryunit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destunit', to='DeliveryApp.deliverunit')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CartApp.orders')),
                ('sourcedeliveryUnit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourceunit', to='DeliveryApp.deliverunit')),
                ('chart_loca', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.deliverychartloca')),
                ('shipmentunit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.shipmentunit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitAuthorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experience', models.PositiveIntegerField()),
                ('user_auth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deliverunitdata',
            name='authoriser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.unitauthorer'),
        ),
    ]
