# Generated by Django 5.0.2 on 2024-04-01 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='deliveryUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.deliverunitdata'),
        ),
    ]
