# Generated by Django 5.0.2 on 2024-04-01 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0003_deliveryunitloca_alter_deliverunitdata_unit_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryunitloca',
            name='userauth',
        ),
    ]
