# Generated by Django 5.0.2 on 2024-04-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0005_unitauthorer_is_active_alter_unitauthorer_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverunitdata',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
