# Generated by Django 5.0.2 on 2024-04-02 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0006_deliverunitdata_is_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverunitdata',
            name='authoriser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.unitauthorer'),
        ),
    ]
