# Generated by Django 5.0.2 on 2024-04-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0008_alter_unitauthorer_user_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychart',
            name='sourcedeliveryUnit',
        ),
        migrations.RemoveField(
            model_name='shipmentunit',
            name='destination_delivery_unit',
        ),
        migrations.RemoveField(
            model_name='deliverychart',
            name='destinationdeliveryunit',
        ),
        migrations.RemoveField(
            model_name='shipmentunit',
            name='source_delivery_unit',
        ),
        migrations.RemoveField(
            model_name='deliverunitdata',
            name='authoriser',
        ),
        migrations.RemoveField(
            model_name='deliverunitdata',
            name='unit_location',
        ),
        migrations.RemoveField(
            model_name='deliveryman',
            name='deliveryUnit',
        ),
        migrations.RemoveField(
            model_name='deliverychart',
            name='chart_loca',
        ),
        migrations.RemoveField(
            model_name='deliverychart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='deliverychart',
            name='shipmentunit',
        ),
        migrations.RemoveField(
            model_name='deliveryman',
            name='userauth',
        ),
        migrations.RemoveField(
            model_name='shipmentunit',
            name='delivery_man',
        ),
        migrations.RemoveField(
            model_name='shipmentitems',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='shipmentitems',
            name='shipment_unit',
        ),
        migrations.RemoveField(
            model_name='unitauthorer',
            name='user_auth',
        ),
        migrations.DeleteModel(
            name='DeliverUnit',
        ),
        migrations.DeleteModel(
            name='DeliveryUnitLoca',
        ),
        migrations.DeleteModel(
            name='DeliverUnitData',
        ),
        migrations.DeleteModel(
            name='DeliveryChartLoca',
        ),
        migrations.DeleteModel(
            name='DeliveryChart',
        ),
        migrations.DeleteModel(
            name='DeliveryMan',
        ),
        migrations.DeleteModel(
            name='ShipmentItems',
        ),
        migrations.DeleteModel(
            name='ShipmentUnit',
        ),
        migrations.DeleteModel(
            name='UnitAuthorer',
        ),
    ]
