# Generated by Django 5.0.2 on 2024-04-03 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CartApp', '0003_orders_buyer'),
        ('DeliveryApp', '0009_remove_deliverychart_sourcedeliveryunit_and_more'),
        ('LandingApp', '0002_userloca_latitude_userloca_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('contact_number', models.CharField(max_length=12, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(default=0)),
                ('current_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_approved', models.BooleanField(default=False)),
                ('user_auth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_loca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LandingApp.userloca')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(max_length=255, null=True)),
                ('is_comleted', models.BooleanField(default=False)),
                ('deliveryboy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.deliveryboy')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CartApp.orders')),
                ('destination_loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_loc', to='DeliveryApp.deliverylocation')),
                ('source_loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_loc', to='DeliveryApp.deliverylocation')),
            ],
        ),
    ]
