# Generated by Django 5.0.2 on 2024-04-03 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0003_orders_buyer'),
        ('DeliveryApp', '0011_alter_deliveryboy_user_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychart',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CartApp.orders'),
        ),
    ]
