# Generated by Django 5.0.2 on 2024-04-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0012_alter_deliverychart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychart',
            name='progress_perc',
            field=models.IntegerField(default=0),
        ),
    ]
