# Generated by Django 5.0.2 on 2024-04-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0013_deliverychart_progress_perc'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychart',
            name='rejected_boys',
            field=models.ManyToManyField(related_name='rejected_boys', to='DeliveryApp.deliveryboy'),
        ),
    ]
