# Generated by Django 5.0.2 on 2024-04-03 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0014_deliverychart_rejected_boys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychart',
            name='destination_loc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_loc', to='DeliveryApp.deliverylocation'),
        ),
        migrations.AlterField(
            model_name='deliverychart',
            name='source_loc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_loc', to='DeliveryApp.deliverylocation'),
        ),
    ]
