# Generated by Django 4.2.6 on 2023-11-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TesterApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentCategory', models.BigIntegerField(null=True)),
                ('categoryName', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catCount', models.IntegerField(default=0)),
                ('productCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerEmail', models.EmailField(max_length=100, null=True)),
                ('categoryid', models.BigIntegerField(null=True)),
                ('productname', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.BigIntegerField(null=True)),
                ('stock', models.PositiveBigIntegerField(null=True)),
                ('imageFile', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('addedate', models.DateTimeField(auto_now_add=True)),
                ('lastChange', models.DateTimeField(null=True)),
                ('pRate', models.IntegerField(null=True)),
                ('validatorID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TesterApp.testerdata')),
            ],
        ),
    ]
