# Generated by Django 4.2.6 on 2023-11-11 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TesterApp', '0001_initial'),
        ('AuthApp', '0001_initial'),
        ('Products', '0002_delete_category_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.BigIntegerField(null=True)),
                ('stock', models.BigIntegerField(null=True)),
                ('Acc_remarks', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('yearOfMan', models.DateField(null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('TesterId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TesterApp.testerdata')),
                ('ownerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productLoca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthApp.userloca')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('categoryId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, null=True)),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('productId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='mcategoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.main_category'),
        ),
    ]
