# Generated by Django 4.2.6 on 2023-11-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='main_category',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='main_category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
