# Generated by Django 4.2.6 on 2023-11-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_category_count_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='categoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Products.category'),
        ),
    ]
