# Generated by Django 4.2.6 on 2023-11-12 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_remove_product_images_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoryid',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='mainCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.main_category'),
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.sub_category'),
        ),
    ]
