# Generated by Django 4.2.6 on 2023-11-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_remove_product_categoryid_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productaddon',
            old_name='productId',
            new_name='product',
        ),
    ]
