# Generated by Django 4.2.6 on 2023-11-12 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_rename_productid_productaddon_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mainCategory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.main_category'),
        ),
    ]
