# Generated by Django 4.2.6 on 2023-11-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_product_maincategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCategory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.sub_category'),
        ),
    ]
