# Generated by Django 4.2.6 on 2023-11-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_product_category_alter_product_maincategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='TesterId',
        ),
    ]
