# Generated by Django 4.2.6 on 2023-11-14 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0012_remove_product_testerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='TesterId',
            field=models.ForeignKey(limit_choices_to={'userRole': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testerid', to=settings.AUTH_USER_MODEL),
        ),
    ]
