# Generated by Django 4.2.6 on 2023-11-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_product_testerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='userResponse',
            field=models.BooleanField(default=False),
        ),
    ]
