# Generated by Django 4.2.6 on 2023-11-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_product_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
