# Generated by Django 4.2.6 on 2023-11-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_product_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='authenticated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='userResponse',
        ),
    ]
