# Generated by Django 4.2.6 on 2023-11-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_remove_product_authenticated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tester_rating',
            field=models.IntegerField(null=True),
        ),
    ]
