# Generated by Django 4.2.6 on 2023-11-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_product_tester_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.IntegerField(null=True),
        ),
    ]
