# Generated by Django 4.2.7 on 2023-12-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_usercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='common_Cart',
            field=models.IntegerField(null=1),
            preserve_default=1,
        ),
    ]
