# Generated by Django 4.2.7 on 2023-12-03 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0021_remove_usercart_common_cart_remove_usercart_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='cartUser',
        ),
        migrations.AddField(
            model_name='usercart',
            name='productImg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productimages'),
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartcount', models.IntegerField()),
                ('totalAmount', models.BigIntegerField(null=True)),
                ('payment_id', models.CharField(max_length=255, null=True)),
                ('cartUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usercart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.usercart')),
            ],
        ),
    ]
