# Generated by Django 4.2.7 on 2023-12-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0022_remove_usercart_cartuser_usercart_productimg_carts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='images',
        ),
    ]
