# Generated by Django 4.2.7 on 2023-12-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_remove_productimages_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
