# Generated by Django 4.2.7 on 2023-12-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_productimages_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='productImg',
        ),
    ]
