# Generated by Django 4.2.7 on 2023-12-03 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0005_alter_userloca_address_mode'),
        ('Products', '0025_remove_usercart_productimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='deliveryLoca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthApp.userloca'),
        ),
    ]
