# Generated by Django 4.2.7 on 2023-12-04 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0026_carts_deliveryloca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='usercart',
        ),
        migrations.AddField(
            model_name='usercart',
            name='usercart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.carts'),
        ),
    ]
