# Generated by Django 4.2.6 on 2023-11-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_remove_product_testerid'),
        ('TesterApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TesterData',
        ),
    ]
