# Generated by Django 4.2.6 on 2023-11-14 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0012_remove_product_testerid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TesterApp', '0002_delete_testerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=14, null=True)),
                ('profilepic', models.ImageField(null=True, upload_to='Testers')),
                ('education', models.CharField(max_length=100, null=True)),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TesterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, null=True)),
                ('acknowledgment', models.CharField(max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TesterApp.testerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TesterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.BigIntegerField(null=True)),
                ('experiance', models.IntegerField(null=True)),
                ('visits', models.IntegerField(null=True)),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TesterApp.testerinfo')),
            ],
        ),
    ]
