# Generated by Django 4.2.6 on 2023-11-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_product_testerid'),
        ('TesterApp', '0004_testerdata_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerinfo',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.category'),
        ),
        migrations.AddField(
            model_name='testerinfo',
            name='main_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.main_category'),
        ),
        migrations.AddField(
            model_name='testerinfo',
            name='sub_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.sub_category'),
        ),
    ]
