# Generated by Django 4.2.6 on 2023-11-14 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TesterApp', '0005_testerinfo_cat_testerinfo_main_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testerinfo',
            name='tester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
