# Generated by Django 4.2.6 on 2023-11-15 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_userloca_street'),
        ('TesterApp', '0006_alter_testerinfo_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerinfo',
            name='tester_loca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthApp.userloca'),
        ),
    ]
