# Generated by Django 4.2.6 on 2023-11-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TesterApp', '0007_testerinfo_tester_loca'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
