# Generated by Django 4.2.6 on 2023-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TesterApp', '0009_remove_testerinfo_is_active_testerdata_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testerdata',
            name='is_active',
        ),
        migrations.AddField(
            model_name='testerinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
