# Generated by Django 4.2.6 on 2023-11-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TesterApp', '0010_remove_testerdata_is_active_testerinfo_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testerinfo',
            old_name='profilepic',
            new_name='profileImage',
        ),
    ]
