# Generated by Django 4.2.6 on 2023-11-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TesterApp', '0011_rename_profilepic_testerinfo_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testerinfo',
            old_name='phone',
            new_name='phoneNumber',
        ),
    ]
