# Generated by Django 4.2.6 on 2023-11-19 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_product_userresponse'),
        ('TesterApp', '0012_rename_phone_testerinfo_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='Testers_Products_Images')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TesterApp.testerinfo')),
            ],
        ),
    ]
