# Generated by Django 5.0.2 on 2024-03-15 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0001_initial'),
        ('LandingApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sold', models.BooleanField(default=False)),
                ('is_tested', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('YearOfMan', models.DateField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('accidents', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('baseprice', models.IntegerField(default=0)),
                ('autobidding', models.BooleanField(default=True)),
                ('testerrating', models.IntegerField(default=0)),
                ('enddatetime', models.DateTimeField(null=True)),
                ('listedtime', models.DateTimeField(null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.brand')),
                ('loca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LandingApp.userloca')),
                ('maincat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.maincategory')),
                ('subcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.subcategory')),
                ('tester', models.ForeignKey(limit_choices_to={'UserRole': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester', to=settings.AUTH_USER_MODEL)),
                ('userauth', models.ForeignKey(limit_choices_to={'UserRole': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userauth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BiddingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_final', models.BooleanField(default=False)),
                ('userauth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_testerimage', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductApp.product')),
            ],
        ),
    ]
