# Generated by Django 5.0.2 on 2024-03-15 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_at_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
