# Generated by Django 5.0.2 on 2024-03-30 16:11

import ProductApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_product_sold_at_datetime_product_sold_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=ProductApp.models.product_image_path),
        ),
    ]
