# Generated by Django 5.0.2 on 2024-04-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0004_alter_product_userauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='itemTrained',
            field=models.BooleanField(default=False),
        ),
    ]
