# Generated by Django 5.0.2 on 2024-04-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0005_product_itemtrained'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_sell_type',
            field=models.IntegerField(default=0),
        ),
    ]
