# Generated by Django 5.0.2 on 2024-03-15 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0001_initial'),
        ('ProductApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0)),
                ('avg_rating', models.IntegerField(default=0)),
                ('workcount', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
                ('registered_tester', models.BooleanField(default=False)),
                ('maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.maincategory')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.subcategory')),
                ('userauth', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TesterServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testdate', models.DateField(null=True)),
                ('testtime', models.TimeField(null=True)),
                ('completed_date', models.DateField(null=True)),
                ('completed_time', models.TimeField(null=True)),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductApp.product')),
                ('testerdata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TesterApp.testerdata')),
            ],
        ),
    ]
